### ISSUE TITLE
Modules can only be executed for single entry in table

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip-scripting#56]
At the moment, modules can only be executed on a single `Module` as otherwise the context is reinjected and an `IllegalStateException` is thrown.

**Comment by Squareys** [comment]
This is because we are reusing the `Module` instance instead of creating a new one from the `ModuleInfo` every time. Are the Service `@Parameters` not cleared? If they aren't it should be sufficient to inject the Context once per Node execution. If they are, were is the IllegalStateException thrown?

**Comment by gab1one** [comment]
This is no longer the case.
